---
title: "Bad Pharma: How medicine is broken, and how we can fix it - Ben Goldacre"
description: |
  Reading notes on some of the chapters. Book on Amazon: [link](https://www.amazon.co.uk/Bad-Pharma-How-Medicine-Broken/dp/000749808X) 
author: "Chi Zhang"
date: "2024-06-06"
categories: [Notes]
sidebar: false
format: 
  html:
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: false
---




## Notes from the book

> Industry funded trials were twenty times more likely to give results that are favoring the test drug

On the need for meta-analysis

> People would write long review articles surveying the literature - in which they would cite the trial data they come across in a completely unsystematic fashion, often reflecting their own prejudice and values.

On trials

> ... mild torture economy: you're not being paid to do a job, you're being paid to endure.

On regulators

> free movement of staff between regulators and drug companies... a fifth of those surveyed said they had been pressured to approve a drug despite reservation about efficacy and safety

> application from large companies, which have greater experience with the regulatory process, pass through to approval faster than those from smaller companies


On surrogate outcomes

> they are approved for showing a benefit on surrogate outcomes, such as blood test, that is only weakly or theoretically associated with the real suffering and death we're trying to avoid. Sometimes drugs which work well to change surrogate outcomes simply don't make any difference to the real outcome.

On comparative effectiveness research

> it is a vitally important filed, in many cases the value of finding out what works best among the drugs we already have would hugely exceed the value of developing entirely new ones.

On safety and efficacy for approved drugs

> 39 percent patients believe that FDA only approves 'extremely effective' drugs, and 25 percent that it only approves drugs without serious side effect. However regulators frequently approve drugs that are only vaguely effective, with serious side effects, on the off-chance that they might be useful to someone, somewhere, when other interventions aren't an option.

On drug reviewing

> Regulators that have approved a drug are often reluctant to take it off the market, in case it is seen as an admissio of their failure to spot problems in the first place

On trial patients

> the 'ideal' patients are likely to get better, they exaggerate the benefits of drugs, and help expensive new medicines appear to be more cost effective than they really are. 'External validity': trial patient being unrepresentative

On comparison drugs

> it is common to see trials where a new drug is compared to a competitor that is known to be useless; or with a good competitor at a stupidly low (or high) dose


On random variation in the data

- early stopping because you peeked in the results. should set up stopping rules, specified before the trial begins
- need a large trial to detect a small difference between two treatments, and a very large trial to be confident that two drugs are equally effective
- (multiple testing, sub-group analysis): measuring lots of things, some will be statistically significant, simply from the natural random variation in all trial data.

On presenting the results

- percent reduction in the risk of heart attack (risk difference)
- relative risk reduction
- presenting the results as relative risk reduction overstates the benefits

Ways trials go wrong

- unrepresentative patients
- too brief 
- measure the wrong outcomes
- go missing, if the result is unflattering
- analysed wrongly

On 'simple trial' using EHR

- at present trials are very expensive. Many struggle to recruit enough patients, many struggle to recruit everyday doctors who don't want to get involved in the mess of filing out patient report forms, calling patients back for extra appointments, doing extra measurements and so on
- simple trials have disadvantage of being not blinded - patients know what drug they've received
- pragmatic trials are cheap
- these trials run forever and follow-up data are easy to get

On marketing 

> Some have estimated that the pharmaceutical industry overall spends twice as much on marketing and promotion as it does on research and developments

> Drugs are advertised more when the number of potential patients, rather than the current patients, is large. 




