---
title: "Use Quarto, Make Friends"
description: "Kolkata UseR meetup"
date: "2024-09-21"
categories: [Community, Quarto]
priority: 1
---

It has been two years since Quarto became the most popular reproducible publication tool in data science and R community. However Quarto is so much more than just a publication tool! I started using it since late 2022, and it has helped me become more organized, productive and connected with people in the data science community.

In this talk I will not focus on the technical aspects on 'how' to use this tool. In the first part of the talk, I would like to report the latest news and trends seen in the useR conference and Posit conf, the two biggest global R events. In the second part, I will share my own experience in using Quarto for my career: from learning new skills, collaborating with co-workers, teaching university courses to networking and building a community (CAMIS collaboration). It is a powerful tool to share your work, and make new connections - both for work and for fun! I hope this talk will provide you with some new ideas on how to use this fantastic technology to fulfill your goals.

{{< video https://www.youtube.com/watch?v=0TEdFZ17FhY >}}
