---
title: "Website reboot: switching from Blogdown to Quarto"
author: "Chi Zhang"
description: |
  Time to reboot the personal website. Now, with Quarto 
date: "2023-01-03"
categories: [Quarto]
title-block-banner: false
---

## From Blogdown to Distill

Since the first time I tried the "academic" template in the popular `blogdown` package in 2019, three years have passed. Back then, it was THE way to build a personal website using R. The "academic" template was notoriously rich in content, and my solution was to delete components, compile, if it works - great; if not, I put the deleted content back. It worked for a while.

When the `distill` package came out (probably in 2020?), I rebooted my website since I preferred its clean, minimalistic style. The look was possibly more appropriate for websites for an organisation or tutorials rather than personal blog, yet I appreciated the simplicity. 

Then I stopped updating my website. Between mid 2020 and early 2022, I was too stressed about completing my PhD, and balancing my other two jobs wasn't the easiest thing. During this period, my mind had been going back to the old site from time to time, but it was hard to find enough time or energy to write about stuff.


## Time to try Quarto

Now that I've finally completed the more pressing tasks in October 2022, I can catch up to the *cool kids* on twitter: create a website with **Quarto**!

There were quite a lot of discussions about Quarto in the summer 2022. I wasn't following the discussions closely, but I remember there were quite a few talks in the Rstudio conference this year. Then more and more people switched to Quarto on Twitter. Then people I know also switched to Quarto. What's the fuzz about?

My experience with Quarto is focused on websites. I have not tried other forms of publishing. So far I have created: 

* a [workshop website](https://ocbe-uio.github.io/2022_bioinformatics_workshop/) for my colleagues

* a personal website (the one you are reading right now)

* an R package ([qtwAcademic](https://andreaczhang.github.io/rpkg/qtwAcademic/))that wraps three Quarto website templates for beginners

Here are a few things I like about Quarto. Given that I'm not very experienced in front-end development, these comments are going to be about ease-of-use and design, rather than the technicalities. 

### Clean look for both personal and workshop/courses

When I was using "academic" template in `blogdown`, I liked the structure of the site: projects, talks, blog, softwares and publications sections are clearly displayed at the top. What I didn't like is that the *default homepage* was a very long single page; yet its customisation wasn't the easist. Other templates were either too simple (for blog only), or more suitable for image display (photography projects). I wanted a website that keep the good structure of "academic", which is quite suitable for academics (hence the name); while keeping each section independent. 

With `distill` I could achieve the structure I wanted; but I didn't enjoy it too much as a personal website (at least it wasn't as flexible as Quarto). `distill` is still pretty decent for organisations or documentation site. 

With Quarto, I can achieve the desired looks for not only a **personal** website (with or without blogs), but also a **workshop, event** or even **course** website. This is fantastic! The top, sidebar or hybrid navigation makes the site structure very clear, especially when there are lots of content. As an aspiring lecturer at university, this is really *One Quarto Rules Them All*. 



### Flexible yet not overwhelming

As I mentioned above, hacking "academic" in `blogdown` was not that easy - simply because there were too many folders that you are not actually supposed to modify. It was confusing to know what to change in order to achieve the desired output, and multiple folders were having the same names, making it very challenging for beginners. Ironically, this is usually the first template beginners start with!

That's why I immediately fell for Quarto: you only need 4 components to make a decent minimalistic website work: 

* `_quarto.yml` to control the overall layout

* `index.qmd` at the root folder to control the homepage

* `about.qmd` for some basic information about the creator or the website

* `project.qmd` for projects or any other content that the creator wants to display

The way that `_quarto.yml` clearly specifies the `.qmd` files really helps beginners to understand where things are. This has been extremely useful for me when I wanted to learn how people made their website by reading the source code - I could understand exactly where to find the information I needed. The clear structure greatly helps the creators themselves, and also those who want to learn. 


### Great community

Rstats people have a great community. I wouldn't be able to make my site the way I wanted if people haven't been sharing their works. I have learned a lot by reading the source code by [Dr Emi Tanaka](https://emitanaka.org), [Dr David Schoch](https://mr.schochastics.net), [Bea Milz](https://beamilz.com), [Prof Mine Cetinnkaya-Rundel](https://mine-cr.com)'s [STA 210 - Regression Analysis](https://sta210-s22.github.io/website/) course. 

I also made my own R package that wraps three templates to create Quarto websites that are frequently used by academics, [qtwAcademic](https://andreaczhang.github.io/qtwAcademic/). In the following days I plan to write up more detailed explanations on how to use the package, along with some new features. 





