---
title: "Personal Highlights: Positconf 2024"
author: "Chi Zhang"
description: |
  My picked talks for 2024 after Posit released the talks on YouTube
date: "2024-11-05"
categories: [Data science]
title-block-banner: false
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
---


## Quarto

[Tyler Morgan-wall: Quarto, AI, and the Art of Getting Your Left Back](https://www.youtube.com/watch?v=U8_Dc_ru8fg&list=PL9HYL-VRX0oSFkdF4fJeY63eGDvgofcbn&index=104)

Transform old blog (Wordpress) to Quarto. Quarto can render pre-exisiting HTML

Customize website with AI, with css

Image carousel, transform some grid images into an auto rotating carousel (JS). Can also add screenshot; explain what the code is doing


### Dashboards

[Alenka Frim and Nic Crane: Mixing R, Python, and Quarto: Crafting the Perfect Open Source Cocktail](https://www.youtube.com/watch?v=8174mk6SGcU&list=PL9HYL-VRX0oSFkdF4fJeY63eGDvgofcbn&index=57)

Comparing the tools to make dashboards:

|   | Dashboard aesthetic  | Markdown syntax | Deploy with GH actions |  Both R and python  |
|:--:|:---:|:--:|:--:|:--:|
| Shiny | Yes| No | No / Yes with Shinylive | Yes|
| Quarto doc | No | Yes | Yes | Yes |
| Quarto dashboard | Yes| Yes | Yes | Yes |


Engine: knitr and jupyter

[Sean Nguyen: Beyond Dashboards: Dynamic Data Storytelling with Python, R, and Quarto Emails](https://www.youtube.com/watch?v=fzykFa6c3LI&list=PL9HYL-VRX0oSFkdF4fJeY63eGDvgofcbn&index=105)

Remove friction of too much dashboards

* logging in can create barriers
* meeting executives where they are (email, for example)
* "no-click" insights (e.g. add key metric/alerts in the subject line or notification)


Tools: **quarto emails**, pins (a package), posit connect

* data sources -> data warehouse (big query) -> quarto (create pins.qmd) -> pins (marketing data.csv pin, for example)
* change quarto format to *email*
* generate multiple using **purrr**




## Python

[Emily Riederer: Python Rgonomics](https://www.youtube.com/watch?v=ILxK92HDtvU&list=PL9HYL-VRX0oSFkdF4fJeY63eGDvgofcbn&index=67)

Python alternatives to R. Worth rewatching! 




## Teaching and education

[Andrew Gard: Teaching and learning data science in the era of AI](https://www.youtube.com/watch?v=kUh3ZAz-Zfg&list=PL9HYL-VRX0oSFkdF4fJeY63eGDvgofcbn&index=82)

Students don't know enough to be able to edit the prompt to reach a sensible code chunk, AI guessed and guessed wrong. We should not expect AI to guess information that we do not provide! 

Students should still learn to code, and teachers should ask better questions - instead of asking for the final result (create a bar plot), ask students to critically think: why doesn't the AI-generated code work? what information is missing? how do you improve the prompt?


[James Wade: Posit Academy in the Age of Generative AI - Lessons from the Frontlines](https://www.youtube.com/watch?v=7tcnho6PHOc&list=PL9HYL-VRX0oSFkdF4fJeY63eGDvgofcbn&index=13)

chattr, gptstudio, github copilot

Posit Academy learners (over half) give AI code assistants 2 star rating or less

Rewarding, high-growth period. **Threshold concepts**: once understood, **transforms** your perception and approach of a discipline, and these must be **encountered** not told.

TC in DS: 

* tidy data enables efficient analysis
* modular code enhances re-usablity and clarity
* visualization as a tool for exploration and communication

How to incorporate AI code assistants (in DS class)

* early stage: explain this code piece by piece
* mid stage: add a roxygen skeleton to my code
* late stage: try code assistants in the IDE

TC for code assistants:

* drive faster but don't forget to steer
* prompting matters, learning how to use these tools is a skill





## Statistics

[Hannah Frick: tidymodels for time-to-event data](https://www.youtube.com/watch?v=NhUGixMJk7U&list=PL9HYL-VRX0oSFkdF4fJeY63eGDvgofcbn&index=20)

[Max Kuhn: Evaluating time-to-event models is hard](https://www.youtube.com/watch?v=cm34R5aYUQ4&list=PL9HYL-VRX0oSFkdF4fJeY63eGDvgofcbn&index=33)

[Demetri Pananos - Making sense of marginal effects](https://www.youtube.com/watch?v=sjYNUIkOlC0&list=PL9HYL-VRX0oSFkdF4fJeY63eGDvgofcbn&index=89)











